name = "website-theme-matrix-qa-7-preview"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-theme-matrix-qa-7-preview-inventory"
database_id = "51ef05eb-48e0-4c53-947c-76639b1e2d66"
