name = "website-theme-matrix-qa-7"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-theme-matrix-qa-7-inventory"
database_id = "6d48ed41-4b49-4d10-828f-4c59e1a5ee50"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "website-theme-matrix-qa-7-images"

[[kv_namespaces]]
binding = "SESSION"
id = "f0b7b4dd06c74b8f8b63e8a2887c63b3"
