name = "website-theme-matrix-qa-7-preview"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-theme-matrix-qa-7-preview-inventory"
database_id = "6a026a78-a395-402b-9e73-0f6f4765362a"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "website-theme-matrix-qa-7-images"

[[kv_namespaces]]
binding = "SESSION"
id = "77aeffc13ad8469e87725b7860447b9a"
