// Generated by Site Launchpad. Edit in the dashboard and export again.
import type { ClientConfigInput } from "./schema";

export const rawClientConfig: ClientConfigInput = {
  "deployMode": "client",
  "identity": {
    "name": "The Hot Tub",
    "shortName": "theme-matrix-qa",
    "foundedYear": 2020,
    "tagline": "Premium outdoor living",
    "siteUrl": "https://theme-matrix-qa.increaseroas.com",
    "schemaType": "HomeAndConstructionBusiness"
  },
  "contact": {
    "phone": "+13135550100",
    "phoneDisplayOverride": "3133132898",
    "smsPhone": "+12489294905",
    "email": "qa@example.com"
  },
  "address": {
    "street": "123 Test Street",
    "street2": null,
    "city": "Detroit",
    "region": "MI",
    "postalCode": "48201",
    "country": "US",
    "latitude": 46.8772,
    "longitude": -96.7898,
    "googlePlaceId": null
  },
  "hours": [
    {
      "days": [
        "Monday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Tuesday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Wednesday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Thursday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Friday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Saturday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    }
  ],
  "social": {
    "facebook": "https://facebook.com/google",
    "instagram": null,
    "youtube": null,
    "tiktok": null,
    "x": null,
    "linkedin": null,
    "googleBusiness": null
  },
  "brand": {
    "colors": {
      "primary": "#476A4E",
      "primaryMid": "#38583F",
      "deep": "#29442F",
      "night": "#1C3021",
      "abyss": "#101D14",
      "accent": "#C88952",
      "accentSoft": "#E0AE81",
      "accentDeep": "#A96938",
      "accentDark": "#76451F",
      "accentLift": "#EDC49E",
      "accentPress": "#A96332",
      "accentGlow": "#F6DDC4",
      "urgent": "#D7261E",
      "urgentLight": "#E8382F",
      "urgentDark": "#B71E17",
      "surface": "#FFFFFF",
      "surfaceAlt": "#F4F2E8",
      "ink": "#141927",
      "inkMuted": "#4A5268",
      "onDark": "#DCE9DE",
      "onDarkMuted": "#A9BEAC"
    },
    "fonts": {
      "display": "Libre Baskerville",
      "body": "Work Sans",
      "mono": "JetBrains Mono",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;500;600;700&family=Work+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap"
    },
    "logos": {
      "nav": "/brand/logo-nav.svg",
      "footer": "/brand/logo-footer.svg",
      "inventory": null,
      "favicon": "/brand/favicon.svg",
      "ogImage": "/brand/og-default.png"
    },
    "radius": {
      "card": 24,
      "button": 12,
      "pill": 999
    }
  },
  "nav": {
    "items": [
      {
        "type": "categories"
      },
      {
        "type": "link",
        "label": "Visit Us",
        "href": "/visit-us",
        "inHeader": true,
        "inFooter": true
      }
    ],
    "primaryCta": {
      "label": "Shop Inventory",
      "href": "/inventory"
    },
    "legalItems": [
      {
        "label": "Privacy Policy",
        "href": "/privacy-policy"
      }
    ]
  },
  "categories": {
    "hot-tub": {
      "enabled": true,
      "label": "Hot Tubs",
      "blurb": "hot tubs near us",
      "heroImage": null,
      "sortOrder": 0
    }
  },
  "serviceAreas": [],
  "financing": null,
  "display": {
    "showPrice": true,
    "showMonthly": false
  },
  "homepage": {
    "title": null,
    "description": null,
    "sections": [
      {
        "type": "hero",
        "eyebrow": null,
        "headline": "Theme Matrix QA 2026-08-18",
        "subhead": "Discover a better way to enjoy your backyard.",
        "actions": [
          {
            "label": "Contact us",
            "href": "/contact",
            "style": "primary"
          }
        ]
      }
    ],
    "disclosures": []
  },
  "integrations": {
    "d1BindingName": "DB",
    "r2BindingName": "PRODUCT_IMAGES",
    "ghl": {
      "enabled": false
    },
    "meta": {
      "enabled": false
    },
    "zaraz": {
      "enabled": false
    },
    "sentry": {
      "enabled": false
    }
  }
};