// Generated by Site Launchpad. Edit in the dashboard and export again.
import type { ClientConfigInput } from "./schema";

export const rawClientConfig: ClientConfigInput = {
  "deployMode": "client",
  "identity": {
    "name": "The Hot Tub",
    "shortName": "theme-matrix-qa",
    "foundedYear": 2020,
    "tagline": "Premium outdoor living",
    "siteUrl": "https://example.com",
    "schemaType": "HomeAndConstructionBusiness"
  },
  "contact": {
    "phone": "+13135550100",
    "phoneDisplayOverride": "3133132898",
    "smsPhone": "+12489294905",
    "email": "qa@example.com"
  },
  "address": {
    "street": "123 Test Street",
    "street2": null,
    "city": "Detroit",
    "region": "MI",
    "postalCode": "48201",
    "country": "US",
    "latitude": 46.8772,
    "longitude": -96.7898,
    "googlePlaceId": null
  },
  "hours": [
    {
      "days": [
        "Monday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Tuesday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Wednesday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Thursday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Friday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Saturday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    }
  ],
  "social": {
    "facebook": "https://facebook.com/google",
    "instagram": null,
    "youtube": null,
    "tiktok": null,
    "x": null,
    "linkedin": null,
    "googleBusiness": null
  },
  "brand": {
    "colors": {
      "primary": "#476A4E",
      "primaryMid": "#38583F",
      "deep": "#29442F",
      "night": "#1C3021",
      "abyss": "#101D14",
      "accent": "#C88952",
      "accentSoft": "#E0AE81",
      "accentDeep": "#A96938",
      "accentDark": "#76451F",
      "accentLift": "#EDC49E",
      "accentPress": "#A96332",
      "accentGlow": "#F6DDC4",
      "urgent": "#D7261E",
      "urgentLight": "#E8382F",
      "urgentDark": "#B71E17",
      "surface": "#FFFFFF",
      "surfaceAlt": "#F4F2E8",
      "ink": "#141927",
      "inkMuted": "#4A5268",
      "onDark": "#DCE9DE",
      "onDarkMuted": "#A9BEAC"
    },
    "fonts": {
      "display": "Libre Baskerville",
      "body": "Work Sans",
      "mono": "JetBrains Mono",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;500;600;700&family=Work+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap"
    },
    "logos": {
      "nav": "/local-assets/clients/7-theme-matrix-qa/astro/navLogo-385b3a53b143cfd0fca210f1101eeab010d9450fbd7c7819485d1996d2fb3cbf-e10107f77fc84675abe718eccdd0bf66.webp",
      "footer": "/local-assets/clients/7-theme-matrix-qa/astro/footerLogo-4fff2d35f2a11e4f5bea9a355a1faa1e7b83c5cea689f765de9d27456b0eedc4-88f3348e66e54daaa753f9ae7bc8c396.webp",
      "inventory": "/local-assets/clients/7-theme-matrix-qa/astro/inventoryLogo-df3a6619de1136710f3fe72fd650a6798236fd0c787fd47f1dc0851f86916d24-e8cbfa8e8db34c3f849d7f1d45503724.webp",
      "favicon": "/local-assets/clients/7-theme-matrix-qa/astro/favicon-d36011f3639f65e6567971e3f2656487024249bf0059e9f0c6928ff0362ec0b1-9387d891d1a44059a68302e604563b5e.webp",
      "ogImage": "/local-assets/clients/7-theme-matrix-qa/astro/ogImage-3bffae80f02af521eb6a112c3a93ecc7128ff4f6dfeb5f1a3437051565fd3a40-011540a01079408eb84b34dff124bedc.webp"
    },
    "radius": {
      "card": 24,
      "button": 12,
      "pill": 999
    }
  },
  "nav": {
    "items": [
      {
        "type": "categories"
      },
      {
        "type": "link",
        "label": "Visit Us",
        "href": "/visit-us",
        "inHeader": true,
        "inFooter": true
      }
    ],
    "primaryCta": {
      "label": "Shop Inventory",
      "href": "/inventory"
    },
    "legalItems": [
      {
        "label": "Privacy Policy",
        "href": "/privacy-policy"
      }
    ]
  },
  "categories": {
    "hot-tub": {
      "enabled": true,
      "label": "Hot Tubs",
      "blurb": "hot tubs near us",
      "heroImage": "/local-assets/clients/7-theme-matrix-qa/astro/categoryHotTubs-eb190e5d11fc0a2d4874ef904bcf940f42079ed8aaeaa44b870420d75739dd7f-0c9aee37f7b3471f96fd5ab71fae62d4.webp",
      "sortOrder": 0
    }
  },
  "serviceAreas": [],
  "financing": null,
  "display": {
    "showPrice": true,
    "showMonthly": false
  },
  "homepage": {
    "title": null,
    "description": null,
    "sections": [
      {
        "type": "hero",
        "eyebrow": null,
        "headline": "Theme Matrix QA 2026-08-18",
        "subhead": "Discover a better way to enjoy your backyard.",
        "actions": [
          {
            "label": "Contact us",
            "href": "/contact",
            "style": "primary"
          }
        ]
      }
    ],
    "disclosures": []
  },
  "integrations": {
    "d1BindingName": "DB",
    "r2BindingName": "PRODUCT_IMAGES",
    "ghl": {
      "enabled": false
    },
    "meta": {
      "enabled": false
    },
    "zaraz": {
      "enabled": false
    },
    "sentry": {
      "enabled": false
    }
  }
};