// Generated by Site Launchpad. Edit in the dashboard and export again.
import type { ClientConfigInput } from "./schema";

export const rawClientConfig: ClientConfigInput = {
  "deployMode": "client",
  "identity": {
    "name": "Sun Pool & Spa Supply",
    "shortName": "theme-matrix-qa",
    "foundedYear": 1978,
    "tagline": "The best hot tub and swim spa store in San Diego County. Real units on the floor.",
    "siteUrl": "https://sunpoolandspasupply.com",
    "schemaType": "HomeAndConstructionBusiness"
  },
  "contact": {
    "phone": "+13135550100",
    "phoneDisplayOverride": "3133132898",
    "smsPhone": "+12489294905",
    "email": "qa@example.com"
  },
  "address": {
    "street": "123 Test Street",
    "street2": null,
    "city": "Detroit",
    "region": "MI",
    "postalCode": "48201",
    "country": "US",
    "latitude": 46.8772,
    "longitude": -96.7898,
    "googlePlaceId": null
  },
  "hours": [
    {
      "days": [
        "Monday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Tuesday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Wednesday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Thursday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Friday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Saturday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    }
  ],
  "social": {
    "facebook": "https://facebook.com/google",
    "instagram": null,
    "youtube": null,
    "tiktok": null,
    "x": null,
    "linkedin": null,
    "googleBusiness": null
  },
  "brand": {
    "colors": {
      "primary": "#16469B",
      "primaryMid": "#0F327A",
      "deep": "#0B2559",
      "night": "#06183D",
      "abyss": "#030C20",
      "accent": "#FFB81C",
      "accentSoft": "#FFCB57",
      "accentDeep": "#E8A400",
      "accentDark": "#8F6400",
      "accentLift": "#FFD46A",
      "accentPress": "#F0A400",
      "accentGlow": "#FFE29A",
      "urgent": "#D7261E",
      "urgentLight": "#E8382F",
      "urgentDark": "#B71E17",
      "surface": "#FFFFFF",
      "surfaceAlt": "#F8F4EC",
      "ink": "#141927",
      "inkMuted": "#4A5268",
      "onDark": "#C6D4EF",
      "onDarkMuted": "#8FA6D2"
    },
    "fonts": {
      "display": "Poppins",
      "body": "Manrope",
      "mono": "JetBrains Mono",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&family=Manrope:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap"
    },
    "logos": {
      "nav": "/brand/logo-nav.svg",
      "footer": "/brand/logo-footer.svg",
      "inventory": null,
      "favicon": "/brand/favicon.svg",
      "ogImage": "/brand/og-default.png"
    },
    "radius": {
      "card": 24,
      "button": 12,
      "pill": 999
    }
  },
  "nav": {
    "items": [
      {
        "type": "categories"
      },
      {
        "type": "link",
        "label": "Visit Us",
        "href": "/visit-us",
        "inHeader": true,
        "inFooter": true
      }
    ],
    "primaryCta": {
      "label": "Shop Inventory",
      "href": "/inventory"
    },
    "legalItems": [
      {
        "label": "Privacy Policy",
        "href": "/privacy-policy"
      }
    ]
  },
  "categories": {
    "hot-tub": {
      "enabled": true,
      "label": "Hot Tubs",
      "blurb": "hot tubs near us",
      "heroImage": null,
      "sortOrder": 0
    }
  },
  "serviceAreas": [],
  "financing": null,
  "display": {
    "showPrice": true,
    "showMonthly": false
  },
  "homepage": {
    "title": null,
    "description": null,
    "sections": [
      {
        "type": "hero",
        "eyebrow": null,
        "headline": "Sun Pool & Spa Supply",
        "subhead": "The best hot tub and swim spa store in San Diego County. Real units on the floor.",
        "actions": [
          {
            "label": "Contact us",
            "href": "/contact",
            "style": "primary"
          }
        ]
      }
    ],
    "disclosures": []
  },
  "integrations": {
    "d1BindingName": "DB",
    "r2BindingName": "PRODUCT_IMAGES",
    "ghl": {
      "enabled": false
    },
    "meta": {
      "enabled": false
    },
    "zaraz": {
      "enabled": false
    },
    "sentry": {
      "enabled": false
    }
  }
};